### ISSUE TITLE
Possible discussion about amazon-genomics-cli with Brazilian bioinformatics team using also AWS + Cromwell

### ISSUE THREAD

**Issue by marcelcaraciolo** [aws/amazon-genomics-cli#113]
[//]: #  Discussion about Amazon Genomics Cli (We are also using cromwell + aws)

**Description**
Hello guys we are studying your study case using amazon-genomics cli, we are a bioinformatics team from Brazil , working the Hospital Israelita Albert Einstein and we saw several issues that we are also facing using AWS + AWS BATCH + WDL + Cromwell. We would like to discuss guys if it's possible to exchange some discussions and ideas. Would it be possible ? We are from the https://github.com/varstation/ (our bioinformatics team from hospital).  Let us know..

Congratulations at your work, it is a huge challenge integrating all these tools with AWS in a smooth and scalable way.

By the way my name is Marcel Caraciolo.

**Comment by miachamp** [comment]
Marcel,
Thank you for your interest in Amazon Genomics CLI and we would appreciate your detailed feedback.  Please send an email (and cc all members of your team) to agc-support@amazon.com.  Feel free to include a description of the issues you mention in your comment as a way for us to start the discussion and we can also schedule virtual calls to follow-up. 
Looking forward to hearing from you.
