### ISSUE TITLE
Design for better `--args` experience

### ISSUE THREAD

**Issue by markjschreiber** [aws/amazon-genomics-cli#120]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

The use of the `--args` has overlaps with the multi file workflow spec, however it was not considered when this was designed leading to inconsistencies and a lack of clarity around how it should be handled with respect to things such as `inputs.json`, `options.json`, `MANIFEST.json` etc

**Proposed Solution**

Produce a design doc and once approved create follow up issued for implementation of the design

**Comment by tneely** [comment]
The design has been completed internally and we've aligned on a path forward. Additional progress will be tracked in  #109.
