### ISSUE TITLE
Links on homepage are unreadable

### ISSUE THREAD

**Issue by alexiswl** [aws/amazon-genomics-cli#135]
Docs home page link: https://aws.github.io/amazon-genomics-cli/#td-block-1

![image](https://user-images.githubusercontent.com/8197659/139757957-8dfc1d30-5989-46e2-8a4d-61d1d75acb8d.png)

**Comment by markjschreiber** [comment]
Are you referring to the color contrast or the content of the link being visible?

If the latter this may be browser dependent (and possibly browser version dependent?). I can see them with Firefox and Chrome but not with Safari.

What Browser/ version/ OS are you using?

**Comment by alexiswl** [comment]
Seeing these colours on both Microsoft Edge and Firefox.

Edge:
https://www.whatsmybrowser.org/b/EZC24

Firefox
https://www.whatsmybrowser.org/b/L646C

**Comment by tneely** [comment]
Hi Alexis, thanks for raising this issue! I'm going to be looking at making the docs more accessible this week, so I'll be sure to improve the contrast/visibility of these links.
