### ISSUE TITLE
Cross region replication of AGC ECR

### ISSUE THREAD

**Issue by miachamp** [aws/amazon-genomics-cli#141]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  Some Customers in global regions outside of US have restrictions on pulling containers from outside regions (e.g. US-east-1).  Need to provide a solution so that they can use AGC. 

**Use Case**

[//]: #  (Why do you need this feature?)
So Customers in global regions (e.g. China, Singapore, etc) can use AGC in cases where they are not permitted to pull assets from outside of their home region. 

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)

https://aws.amazon.com/blogs/containers/cross-region-replication-in-amazon-ecr-has-landed/

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by tneely** [comment]
Some background: we publish ECR artifacts to us-west-2 and replicate in us-east-1. By default, [AGC always pulls images from us-east-1](https://github.com/aws/amazon-genomics-cli/blob/main/packages/cli/internal/pkg/environment/environment.go#L10), though we have an escape hatch for specifying other regions.

I propose we either
1. Replicate in every region and pull from whatever region the customer runs in
2. Replicate in a few major regions across the world and fall back to the nearest region from the customer

**Comment by miachamp** [comment]
Thanks Taylor -
I believe it will have to be option #1 to comply with the regulations of some of the regions where our Customers reside.  For several regions, healthcare organizations are strictly prohibited from sharing/pulling data or tooling from outside of their region.  So, they would be required to pull from the same region they run AGC in.
