### ISSUE TITLE
Installation docs out of date - 'latest' release does not exist, zip structure has changed

### ISSUE THREAD

**Issue by alexiswl** [aws/amazon-genomics-cli#177]
From the docs page [here](https://aws.github.io/amazon-genomics-cli/docs/getting-started/installation/)

```
curl -OLs https://github.com/aws/amazon-genomics-cli/releases/latest/download/amazon-genomics-cli.zip
unzip amazon-genomics-cli.zip -d agc
./agc/install.sh
```

## Missing release

Running 
```
curl -OLs https://github.com/aws/amazon-genomics-cli/releases/latest/download/amazon-genomics-cli.zip
$ cat amazon-genomics-cli.zip
```

Yields:

```
Not Found%     
```

These probably aren't the parameters I would use for curl either.  

Using `--fail` or `-f` would at least return a non-zero exit code if the url did not exist.  

When using `--silent` or `-s`, one needs to be very confident that the url exists or that errors are handled correctly.  In this case, even with `-f` the user is none-the-wiser that the url does not exist.  

I would instead recommend using 
```
curl -OLf https://github.com/aws/amazon-genomics-cli/releases/latest/download/amazon-genomics-cli.zip
```

which yields

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   157  100   157    0     0    457      0 --:--:-- --:--:-- --:--:--   456
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
```

## Zip restructure

Step 1: Download the latest release
```
curl -OLs https://github.com/aws/amazon-genomics-cli/releases/download/v1.1.0/amazon-genomics-cli-1.1.0.zip
```

Step 2: Unzip into the agc directory
```
unzip amazon-genomics-cli.zip -d agc
```

Step 3: Look in the directory
```
% ls agc         
```

Yields:
```
amazon-genomics-cli
```

`./agc/install.sh` does not exist! 

With the latest release we can instead do:
```
unzip amazon-genomics-cli.zip
bash amazon-genomics-cli/install.sh 
```

**Comment by alexiswl** [comment]
Looks like this was fixed in https://github.com/aws/amazon-genomics-cli/pull/161 but is yet to be pushed to the site

**Comment by nbraid** [comment]
Thanks for reporting this @alexiswl. There was an issue with our docs publishing action that has been fixed now. The documentation at https://aws.github.io/amazon-genomics-cli/docs/getting-started/installation/#download-and-install-amazon-genomics-cli has been updated.
