### ISSUE TITLE
version upgrade doesn't take effect

### ISSUE THREAD

**Issue by bounlu** [aws/amazon-genomics-cli#178]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

I have upgraded `agc` to the latest version released `v1.1.0`.

However, when I check for the version it still shows the old version:

```
$ agc --version
agc version: 1.0.1-1-gfd7b94a
```

Moreover, when I open a new Terminal window, I get the notification:

`$ 2021-11-16T12:35:19+08:00 𝒊  New version of agc available. Current version is '1.0.1'. The latest version is '1.1.0'`

**Steps to Reproduce**

```
wget https://github.com/aws/amazon-genomics-cli/releases/download/v1.1.0/amazon-genomics-cli-1.1.0.zip
unzip amazon-genomics-cli-1.1.0.zip
./amazon-genomics-cli-1.1.0.zip/install.sh

agc --version
```

Operating System: macOS Monterey 12.0.1
AGC Version: 1.1.0
Was AGC setup with a custom bucket: no
Was AGC setup with a custom VPC: no

**Comment by tneely** [comment]
We changed our release process for v1.1.0 and unfortunately missed this use case. This has been addressed in #164. Future releases should print the correct version.
