### ISSUE TITLE
Remove requirement for Docker during Context Deploy

### ISSUE THREAD

**Issue by markjschreiber** [aws/amazon-genomics-cli#185]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  (A short description of the feature you are proposing.)
With the addition of WES as a Lambda service we started deploying the required python libs with containerization (the cdk default). This adds two minutes to each deployment and seems to occasionally get stuck during the container build. Adds a dependency on Docker.

**Use Case**

[//]: #  (Why do you need this feature?)

We need to reduce context deployment time and make it as reliable as possible.

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)

Look into providing the required python libs as a layer/ zip file from our public assets account or add to customers S3 during account initialization?

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by eddie1183** [comment]
Merged and will be part of the next release.
