### ISSUE TITLE
EBS data volume not mounted for some Nextflow jobs

### ISSUE THREAD

**Issue by snamburi3** [aws/amazon-genomics-cli#186]
Some of the jobs submitted with Nextflow do not mount the 200GB data disk, resulting in "No space left on device" error. This happens only with a few random jobs.

**Steps to Reproduce**

agc workflow run demo-nextflow-project --context spotCtx

**Relevant Logs**

I get this below error:
 |abort: write error ....(No space left on device)

Doing a df -h on the instance shows the 200GB disk (/dev/nvme1n1) not being mounted:

>>  df -h
  | Filesystem Size Used Avail Use% Mounted on
  | overlay 30G 9.4G 20G 33% /
  | tmpfs 64M 0 64M 0% /dev
  | tmpfs 5.0G 0 5.0G 0% /sys/fs/cgroup
  | /dev/nvme0n1p1 30G 9.4G 20G 33% /opt/aws-cli
  | shm 64M 0 64M 0% /dev/shm
  | tmpfs 5.0G 0 5.0G 0% /proc/acpi
  | tmpfs 5.0G 0 5.0G 0% /sys/firmware

**Expected Behavior**
Mount the 200GB disk (/dev/nvme1n1 ) on /
>> df -h
 | Filesystem Size Used Avail Use% Mounted on
 **| /dev/nvme1n1 200G 12G 188G 6% /**
 | tmpfs 64M 0 64M 0% /dev
 | tmpfs 3.8G 0 3.8G 0% /sys/fs/cgroup
 | /dev/nvme0n1p1 30G 6.4G 23G 22% /opt/aws-cli
 | /dev/nvme1n1 200G 12G 188G 6% /etc/hosts
 | shm 64M 0 64M 0% /dev/shm
 | tmpfs 3.8G 0 3.8G 0% /proc/acpi
 | tmpfs 3.8G 0 3.8G 0% /sys/firmware

**Actual Behavior**

See above expected behavior

Operating System:
AGC Version: agc version: 1.0.0-41-gc5ac696
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: No

**Comment by snamburi3** [comment]
I noticed that this is mostly happening with the M5n,  R5n, C5n instances types.

Here is the error message:
```

+ systemctl enable amazon-ssm-agent
+ systemctl start amazon-ssm-agent
Job for amazon-ssm-agent.service canceled.
 util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
 cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed

``

**Comment by AndreyDovydenko** [comment]
Hello snamburi3! Could you please help us tracing this issue down by pointing us which workflow ends up giving you this error? Is it any of the workflows  defined in the `demo-nextflow-project` or anything else that you have tried to run?

**Comment by snamburi3** [comment]
Thank you, Andrey. It is the workflow defined in the `demo-nextflow-project`. Also, please ignore my above comment that this happens only on the M5n, R5n, C5n instances types. I have seen this happen with other instance types as well like M5, R5, C5 instances types. Some of the instances just fail to mount the  /dev/xvdba disk as user scripts on the instance fail to run.

**Comment by markjschreiber** [comment]
Both of this and #40 indicate that the EC2 instances are not correctly provisioning their dependencies. I will add a new feature request for better validation of provisioning and close these issues in favor of that.

**Comment by markjschreiber** [comment]
Checking in on this ticket. Is this a problem that you have had consistently with this workflow or is this a sporadic issue? If it is the latter we are working on some solutions to make provisioning of the dependencies more reliable. If it is a consistent issue there may be a different problem we need to investigate.

**Comment by GallVp** [comment]
Hi @markjschreiber 

Thanks for your work on this. I have been experimenting the usage of AGC with NextFlow. The EBS autoscale generally works really well. However, it fails when multiple large files are being staged by NextFlow at the same time. I think the source of failure is this line in `awslabs/amazon-ebs-autoscale`: https://github.com/awslabs/amazon-ebs-autoscale/blob/a55e7cc8913dd89e42b4668e4e8883209db26e9c/bin/ebs-autoscale#L209

```bash
STATS=$(df -BG  ${MOUNTPOINT} | grep -v Filesystem)
TOTAL_SIZE=$(echo ${STATS} | awk '{print $2}')
USED=$(echo ${STATS} | awk '{print $3}')
``` 

The stats are based on the `df` command which under reports when multiple files are being copied to a directory inside `${MOUNTPOINT}`. I think it can be fixed by using `du` as in:

```bash
USED=$(du -BG -d 0 ${MOUNTPOINT} | awk '{print $1}')
``` 

This patch can be applied to the `awslabs/amazon-ebs-autoscale` copy included with AGC: https://github.com/aws/amazon-genomics-cli/blob/main/packages/cdk/lib/artifacts/batch-artifacts/amazon-ebs-autoscale.tgz

Cheers
Usman R.
