### ISSUE TITLE
Unclear documentation on behaviour when source URL is a directory 

### ISSUE THREAD

**Issue by multimeric** [aws/amazon-genomics-cli#207]
In the [workflows](https://aws.github.io/amazon-genomics-cli/docs/concepts/workflows/) page, it seems like it is going to explain how to provide directories as workflow URLs, but it actually only explains behaviour for workflow files:
> When a **directory** is supplied as the sourceURL, Amazon Genomics CLI uses the following rules to determine the name of the main workflow file and any supporting files:
> 1. If the source URL resolves to a single non-zipped **file**...
> 2. The source URL resolves to a zipped **file** (.zip)...

**Comment by markjschreiber** [comment]
Good call out. The actual behavior is the same as for a zip file (if the directory was zipped up). We should make this explicit in the docs.

**Comment by markjschreiber** [comment]
Updated description of multifile workflows to include the case when the URL references a directory (see point 3 of https://aws.github.io/amazon-genomics-cli/docs/concepts/workflows/#multi-file-workflows)
