### ISSUE TITLE
Document manifest file

### ISSUE THREAD

**Issue by multimeric** [aws/amazon-genomics-cli#210]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

Documentation explaining the manifest file and its contents specifically would be helpful. It's currently mentioned incidentally on a few pages ([e.g. here](https://aws.github.io/amazon-genomics-cli/docs/concepts/workflows/#multi-file-workflows)), but has no dedicated section.

**Use Case**

I want to write a manifest, but am unsure how

**Proposed Solution**

Description of all the keys in the manifest file and their meaning, in a dedicated page of the documentation.

**Comment by markjschreiber** [comment]
Production docs are now updated https://aws.github.io/amazon-genomics-cli/docs/concepts/workflows/#manifestjson-structure

**Comment by multimeric** [comment]
Thanks! That's super useful.
