### ISSUE TITLE
move nightly builds to a different repo, to reduce excess notifications

### ISSUE THREAD

**Issue by mr-c** [aws/amazon-genomics-cli#241]
Currently, those of use to subscribe to releases here get a notification for every nightly release in addition to the regular releases. Can those asserts be stored elsewhere, to reduce excess notifications?

**Comment by a-li** [comment]
We have moved our nightly build to a public S3 bucket here: `s3://healthai-public-assets-us-east-1/amazon-genomics-cli/nightly-build/amazon-genomics-cli.zip` It will no longer be published to GitHub. 

You may download the nightly builds using this command (or similar):
`aws s3api get-object --bucket healthai-public-assets-us-east-1 --key amazon-genomics-cli/nightly-build/amazon-genomics-cli.zip amazon-genomics-cli.zip`

**Comment by mr-c** [comment]
Thank you very much @a-li !
