### ISSUE TITLE
docs: clarify how multiple input files are used if specified in workflow MANIFEST

### ISSUE THREAD

**Issue by wleepang** [aws/amazon-genomics-cli#251]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  (A short description of the feature you are proposing.)

Workflow MANIFEST files allow specifying multiple input files to be passed to underlying engines. Clarify how they are used, ideally with some examples.

**Use Case**

[//]: #  (Why do you need this feature?)

Avoid confusion on how multiple input files are used.

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)

Provide documentation like the following for expected behaviors for supported engines.

> When using Cromwell, if multiple files are listed in `MANIFEST.inputFiles`, they will be passed to Cromwell in the order specified as `workflowInput.json, workflowInput_1.json, ... , workflowInput_5.json`. (Note: Cromwell only supports up to 5 input.json files). If there are any properties in common between the files, values in higher numbered files will take precedence. (See: https://cromwell.readthedocs.io/en/stable/api/RESTAPI/#submit-a-workflow-for-execution)

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by josuebc** [comment]
Changes were merged
