### ISSUE TITLE
Tag infrastructure with custom tags to prevent automatic deletion

### ISSUE THREAD

**Issue by adamnovak** [aws/amazon-genomics-cli#254]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  (A short description of the feature you are proposing.)

In our infrastructure, we automatically delete AWS resources, such as buckets and instances, that do not have an "Owner" tag set. This is for cost control, to ensure that AWS costs are always attributable to someone.

AGC does not seem to apply this tag to its buckets or instances, so they are being automatically deleted.

AGC needs a way to specify (during account activation at least, and potentially when contexts are deployed and workflows are run) custom tags, or at least an "Owner" tag, to be applied to all taggable resources (or at least the CF stack that owns them).

**Use Case**

[//]: #  (Why do you need this feature?)

This is required to use AGC in UCSC's environment, without its resources being deleted out from under it.

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)

The `cdk bootstrap` and `cdk deploy` commands have a `--tags` option that takes `name=value` pairs of tags to apply to the created stack. AGC ought to support the same option, and ideally apply the tags to all resources, instead of just the stack.

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by adamnovak** [comment]
It looks like having the tag on the stack is sufficient for it to automatically propagate to all the resources.

The workaround here is to quickly jump in after the stack is created and before its resources can be deleted, and use the console to create a new change that adds an Owner tag to the stack, and apply it.

**Comment by adamnovak** [comment]
My workaround doesn't quite actually work for instances. Neither I nor CloudFormation can edit an AWS Batch Compute Environment to add tags to it once it is created. So adding the tag to the CF stack after initial setup doesn't seem to get it applied to the CE, and therefore it doesn't end up on the instances.

**Comment by waliag87** [comment]
Hello! Thank you for the feature request. We are have started discussing this internally and will provide an update afterwards.

**Comment by markjschreiber** [comment]
Capability added in 1.3.0
