### ISSUE TITLE
Eliminate the need for MacOS users to override Security settings when installing AGC binary

### ISSUE THREAD

**Issue by a-li** [aws/amazon-genomics-cli#268]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  (A short description of the feature you are proposing.)
Provide a way for users to download the AGC binary from an "Apple-trusted" source without having to manually override the security setting.

**Use Case**

[//]: #  (Why do you need this feature?)
Currently if users download and install the AGC binary on MacOS, they need to override the Privacy and Security setting and deal with several popup windows in order to install properly. Although instructions are provided in the installation guide, this is definitely not ideal as it requires extra manual steps. 

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)

1. Sign the AGC binary with the Apple Amazon Developer key
2. (OR) Add AGC into `brew aws/tap` (https://github.com/aws/homebrew-tap) so it can be downloaded directly from brew. 

The homebrew solution is more robust and can work on both MacOS and Linux. 

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by ghawk1ns** [comment]
In the short term, to avoid quarantine, you can use curl to download the AGC zip 

```
curl -Lo amazon-genomics-cli-1.1.1.zip https://github.com/aws/amazon-genomics-cli/releases/download/v1.1.1/amazon-genomics-cli-1.1.1.zip
```

the installed agc binary downloaded this way, at least for now, won't be quarantined.
