### ISSUE TITLE
Ongoing cost reduction options

### ISSUE THREAD

**Issue by multimeric** [aws/amazon-genomics-cli#269]
**Description**

I would like the AGC to offer greater control over AWS resources that have an ongoing cost associated with them. Particularly the NAT Gateway and VPC Endpoints.

[//]: #  (A short description of the feature you are proposing.)

**Use Case**

Many AWS users including myself are concerned about keeping costs down. In particular my use case involves keeping the AGC stack "up" for an extended period of time to support a bioinformatics web tool, so ongoing costs are a big problem.

In particular, the main ongoing costs I would like to see addressed are:
* The NAT Gateway. My monthly bill from NAT from the AGC was $41.72 USD
* VPC Endpoints. My month bill from these endpoints was $21.24 USD

Of course, these costs are dwarfed by the EC2 compute costs and data transfer costs in many use cases, but for my above scenario they are not, which is why I would like the AGC to provide the ability to help address these.

**Proposed Solution**

I don't understand the AGC stack fully, but I suspect that both of these services are only specifically needed by the "head job", ie the workflow manager job. I can't imagine that average bioinformatics jobs require internet access and/or AWS access. So a simple solution then is to put the head node into a public subnet, with a heavily locked-down security group, so that it can receive no public traffic at all. Then, I believe we could drop both the VPC Endpoints and the NAT gateway used by that job, since the public subnet allows the same access.

It might be possible to modify the default stack to do this, without breaking any use cases. However if this is not possible, I could envisage a new key in the context object in the `agc-project.yaml`, along the lines of `publicSubnet: true`, which would enable this functionality.

**Comment by markjschreiber** [comment]
Hi, thanks for your feedback. 

Most nodes require some access to the internet or AWS services like S3, Parameter store, ECR and CloudWatch. For example, workflow tasks are containerized and frequently access inputs from S3 and/ or shared storage like EFS. They also need to communicate with the Batch cluster and CloudWatch to coordinate and provide logging.

The current configuration, using private subnets and VPC endpoints is the best practice for security posture and the use of private subnets and endpoints is a requirement of many organizations. As you note however, it does add some on-going costs.

It is possible to use AGC with an existing VPC to avoid any additional costs of having an extra VPC. This VPC will still require private subnets but it could help avoid paying for additional NAT gateways. To do this you would provide the ID of the existing VPC when activating AGC. https://aws.github.io/amazon-genomics-cli/docs/reference/agc_account_activate/ 

We can take a look at an option to use public subnets but we would need to carefully inspect security and compatibility.

**Comment by multimeric** [comment]
Thanks for the reply. Would you accept a PR with an (opt-in) config option to use public subnets?

**Comment by markjschreiber** [comment]
Hi, yes we would be open to a PR with this option. As it involves security we would want to review the submission with our security teams to make sure it doesn't inadvertently expose data or create unnecessary vulnerabilities before we would merge the PR. We would of course give you any feedback on the security posture of the proposal.

When developing the option please be aware that there are places in the CDK package that assume the existence of private subnets such as `https://github.com/aws/amazon-genomics-cli/blob/73bb98d23a18f210d4bfa231b0f8002bb294529c/packages/cdk/lib/stacks/core-stack.ts#L99` which will need to be modified appropriately or placed into a control flow block (such as an `if` statement).

**Comment by miachamp** [comment]
Michael,
Thank you for submitting this GitHub issue.
 
I’m a Sr. Product Manager with AWS HealthAI and I would like to set up a call to discuss your SIM submission in more detail , and will also be joined by member/s from our engineering team.
 
If you are interested in discussing in more detail, please provide your current email address.

Thanks,
Mia Champion

**Comment by multimeric** [comment]
Thanks for the guidance @markjschreiber. I understand the need for a security review.

Hi @miachamp, I'm happy to discuss this PR. What aspect of it needs discussion? Also what is a SIM? My email is <michael.r.milton@gmail.com>.
