### ISSUE TITLE
S3 retry for Cromwell logic doesn't work

### ISSUE THREAD

**Issue by elliot-smith** [aws/amazon-genomics-cli#275]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

Currently, if an S3 download fails when Cromwell is being setup, the loop logic will fail as the value is being cast to a string. The logic is currently

`
sleep $((7 * "$i"))
`
but it should be 
`
sleep $((7 * i))
`

Also, there is some duplicate logic in there that could be refactored out as well as some additional logs for assisting with troubleshooting

**Steps to Reproduce**

[//]: #  (Include a list of steps that can be used to reproduce the bug.)

Run a workflow that fails to download the S3 contents for the first time.

**Relevant Logs**

`
attempt 1 to copy s3://agc-383881756834-us-west-2/project/Demo/userid/elliotsm3WJrU7/context/myContext/cromwell-execution/Words_With_Vowels/fa3208ab-92b6-445b-9044-35ed9de948a6/call-FindWordsWithLetter/shard-0/script failed
--
/tmp/tmp.pLTmOLrXI/batch-file-temp: line 33: 7 * "1": syntax error: operand expected (error token is ""1"")
grep: /tmp/scratch/agc-383881756834-us-west-2/project/Demo/userid/elliotsm3WJrU7/context/myContext/workflow/words-with-vowels/mieliestronk-words.txt: No such file or directory

`

**Expected Behavior**
The download logic loops

**Actual Behavior**
The download fails and the loop logic is skipped

**Additional Context**

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System:
AGC Version: Built from source on 1/21
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: No

**Comment by markjschreiber** [comment]
Closed by PR #300
