### ISSUE TITLE
Node executables not being installed on main branch

### ISSUE THREAD

**Issue by multimeric** [aws/amazon-genomics-cli#292]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

[//]: #  (Please describe the behavior that you are seeing with as many details as possible including logs from AGC, CloudWatch snippets and CloudFormation errors if relevant.)
I'm getting `sh: 1: ts-node: not found` when I `agc account activate` when using the latest code off the main branch.

**Steps to Reproduce**

```
git clone git@github.com:aws/amazon-genomics-cli.git
cd amazon-genomics-cli
make release
./dist/amazon-genomics-cli/install.sh
agc account activate
```

**Relevant Logs**

```
2022-02-01T14:05:56+11:00 𝒊  Activating AGC with bucket '' and VPC ''
Bootstrapping CDK... [-o--] 1.8s                                                                                                                                                                                   2022-02-01T14:06:01+11:00 ✘  sh: 1: ts-node: not found
2022-02-01T14:06:01+11:00 ✘  Subprocess exited with error 127
2022-02-01T14:06:01+11:00 ✘   error="exit status 1"
Error: an error occurred invoking 'account activate'
with variables: {bucketName: vpcId: publicSubnets:false}
caused by: exit status 1
```

**Expected Behavior**

The core stack to be deployed,

**Actual Behavior**

The above error

**Additional Context**

I think this involves the fact that the `npm-shrinkwrap.json` is missing the binaries, when it shouldn't be. If I run `npm shrinkwrap` on the previous (stable) release, I get a shrinkwrap file that includes the binaries, such as the one causing this issue:
```json
    "node_modules/ts-node": {
      "version": "10.4.0",
      "resolved": "https://registry.npmjs.org/ts-node/-/ts-node-10.4.0.tgz",
      "integrity": "sha512-g0FlPvvCXSIO1JDF6S232P5jPYqBkRL9qly81ZgAOSU7rwI0stphCgd2kLiCrU9DjQCrJMWEqcNSjQL02s6d8A==",
      "dev": true,
      "bin": {
        "ts-node": "dist/bin.js",
        "ts-node-cwd": "dist/bin-cwd.js",
        "ts-node-script": "dist/bin-script.js",
        "ts-node-transpile-only": "dist/bin-transpile.js",
        "ts-script": "dist/bin-script-deprecated.js"
      },
    },
```

However if we look at the current shrinkwrap file, you will notice that there are no `"bin"` keys in the JSON structure at all: https://github.com/aws/amazon-genomics-cli/blob/d803ed4c67e8f82835e0e9f9ae13b33a72e69ae1/packages/cdk/npm-shrinkwrap.json

Operating System:
AGC Version: d803ed4c67e8f82835e0e9f9ae13b33a72e69ae1
Was AGC setup with a custom bucket: No
Was AGC setup with a custom VPC: No

**Comment by tneely** [comment]
Thanks for flagging this. I'm looking into it now.
