### ISSUE TITLE
Speedup 5x S3 download using latest nextflow downloadParallel setting

### ISSUE THREAD

**Issue by ArlindNocaj** [aws/amazon-genomics-cli#303]
**Description**
nextflow has very slow download of s3 which I can observe using an ec2 instance and bmon.

The latest nextflow-edge version seems to have multipart download and speedup possibility as described here: https://github.com/nextflow-io/nextflow/issues/2150

```
aws.client.downloadParallel = true
other config settings:

aws.client.downloadChunkSize = '10 MB' // size of the downloaded chunk 
aws.client.downloadNumWorkers = 10     // number of download worker threads
aws.client.downloadBufferMaxSize = '1 GB' // max size of heap buffer to store temporary store chunks 
aws.client.downloadMaxAttempts = 5     // number of attempts for a failed chunk download
```

**Use Case**

Running large genomics flows requires downloading of very large files, e.g. nf-core/sarek (25-100GB input files).
A speed of 50mb/s compared to 200-250 mb/s clearly slows down the overall process.

**Proposed Solution**

add latest nextflow settings above to speedup using multipart download.

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by ArlindNocaj** [comment]
Using the latest nextflow edge, I can confirm that download rate goes up to 268 MB/s.

```
nextflow info
  Version: 21.12.1-edge build 5653
  Created: 22-12-2021 07:53 UTC
  System: Linux 5.10.93-87.444.amzn2.x86_64
  Runtime: Groovy 3.0.9 on OpenJDK 64-Bit Server VM 1.8.0_312-b07
  Encoding: UTF-8 (ANSI_X3.4-1968)
``
<img width="632" alt="Screenshot 2022-02-03 at 16 27 41" src="https://user-images.githubusercontent.com/2978097/152373736-d30f0b88-0195-4365-8730-c9bb10e44627.png">
`

**Comment by tneely** [comment]
We currently use an older version of Nextflow (21.04.3), but will look into enabling this feature once we evaluate and upgrade to the latest release.
