### ISSUE TITLE
Snakemake - Retry mechanisms

### ISSUE THREAD

**Issue by elliot-smith** [aws/amazon-genomics-cli#320]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  (A short description of the feature you are proposing.)
Snakemake workflows are all run in separate locations which means that previous steps need to be retried if a customer runs a workflow twice. We should allow customers the ability to run workflows in a specific folder for snakemake so that the workflow can skip through previous steps.

**Use Case**

[//]: #  (Why do you need this feature?)
It allows customers to dynamically test and validate complex workflows without repeating previous steps.

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)
Allow the customer to specify a folder to run the workflow in that will be consistently used between runs.

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by nh13** [comment]
Would welcome this, especially for large workflows
