### ISSUE TITLE
List of permissions to use agc

### ISSUE THREAD

**Issue by ElDeveloper** [aws/amazon-genomics-cli#383]
I am trying to setup a new user with AGC and after running `agc account activate` I get a variety of different errors, most related to missing permissions, etc. Is there a list of required permissions that should be enabled for a user in order to get all of AGC to work?

**Comment by elliot-smith** [comment]
Hi ElDeveloper,
There is a list of permissions that are required that are available here: https://github.com/aws/amazon-genomics-cli/tree/main/extras/agc-minimal-permissions

**Comment by ElDeveloper** [comment]
Thanks @elliot-smith, didn't quite understand that `agc account activate` should be run with admin level privileges to setup the environment **and** then I should use the created policies to grant access to non-admin users (i.e. `AgcPermissionsStack-agcuserpolicy*` and `AgcPermissionsStack-agcuserpolicycdk*`).
