### ISSUE TITLE
Files in inputs json are relative to json file rather than relative to $PWD

### ISSUE THREAD

**Issue by alexiswl** [aws/amazon-genomics-cli#39]
Hello, one change I've noticed from agc release 0.81 to 1.0.0 has been that input files are now relative to the input json rather than relative to the current working directory.  

### Project yaml
For example, in the directory `myproj` I have the following `agc-project.yaml`:  

<details>
<summary>Click to expand!</summary>

```yaml
name: myproj
schemaVersion: 1

workflows:
  read:
    type:
      language: wdl
      version: 1.0
    sourceURL: ../../workflows/read.wdl

contexts:
    ctx1:
        engines:
            - type: wdl
              engine: cromwell
```

</details>

With the following directory tree:
```
.
├── agc-project.yaml
├── startup.log
├── workflow_inputs
│   ├── data.txt
│   └── read.inputs.json
```

And `../../workflows/read.wdl` is:

<details>

<summary>Click to expand!</summary>

```wdl
version 1.0
workflow ReadFile {
    input {
        File input_file
    }
    call read_file { input: input_file = input_file }
}

task read_file {
    input {
        File input_file
    }
    String content = read_string(input_file)

    command {
        echo '~{content}'
    }
    runtime {
        docker: "ubuntu:latest"
        memory: "4G"
    }

    output { String out = read_string( stdout() ) }
}
```

</details>

## Inputs Overview
The contents of `workflow_inputs/read.inputs.json` are as follows:
```json
{
    "ReadFile.input_file": "workflow_inputs/data.txt"
}
```

## Workflow run command

Running the agc workflow command:
```
$ agc workflow run read --args workflow_inputs/read.inputs.json --context ctx1
```

yields

```
2021-09-29T15:53:06+10:00 𝒊   Running workflow. Workflow name: 'read', Arguments: 'workflow_inputs/read.inputs.json', Context: 'ctx1'
2021-09-29T15:53:07+10:00 ✘   error="unable to run workflow: stat /c/Users/awluc/OneDrive/GitHub/UMCCR/agc-dev-notes/examples/projects/myproj/workflow_inputs/workflow_inputs/data.txt: no such file or directory"
Error: an error occurred invoking 'workflow run'
with variables: {WorkflowName:read Arguments:workflow_inputs/read.inputs.json ContextName:ctx1}
caused by: unable to run workflow: stat /c/Users/awluc/OneDrive/GitHub/UMCCR/agc-dev-notes/examples/projects/myproj/workflow_inputs/workflow_inputs/data.txt: no such file or directory
```

Changing the input json to:
```json
{
    "ReadFile.input_file": "data.txt"
}
```

resolves the error.  

Given a user may want to create an input json in temp space, I would have thought that the paths should be relative to the current working directory instead of being relevant to the location of the input json file.

**Comment by wleepang** [comment]
The way AGC handles inputs is specific to the way it deploys and interacts with workflow execution resources.

cwltool doesn't have cloud execution capabilities as far as I'm aware. Inputs provided via `inputs.json` files for Cromwell are typically either cloud locations (like S3 URIs) or files relative to a `workflowDependencies` zip file submitted along with the request.

**Comment by nbraid** [comment]
Echoing Lee's comments: AGC aims to be reproducible, meaning running a workflow with a given inputs.json in a given project should work the same way, regardless of your current working directory. At the moment, we don't think this is something we're going to change. If you feel it warrants further discussion, feel free to reopen this issue!
