### ISSUE TITLE
Hugo documentation build fails and produces broken docs

### ISSUE THREAD

**Issue by adamnovak** [aws/amazon-genomics-cli#416]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

[//]: #  (Please describe the behavior that you are seeing with as many details as possible including logs from AGC, CloudWatch snippets and CloudFormation errors if relevant.)

Using the current stable Hugo Extended snap package on Linux, the documentation build with `hugo` fails. I get content in `docs/`, but if I host it with `http-server`, the images and stylesheets don't load due to missing files and subresource integrity failures.

If I run `hugo server -D`, the initial build of the documentation fails with the same log, and the server does not start.

**Steps to Reproduce**

[//]: #  (Include a list of steps that can be used to reproduce the bug.)

1. Have an Ubuntu 20.04 machine.

2. Run these commands:
```
git checkout cc838eff100f1ef5b97439c298035542f2d6cc23
git submodule update --init --recursive
cd site
npm install
sudo snap install hugo --channel=extended/stable
hugo version
# I got: hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=mage
hugo
# I get a log of complaints
echo $?
# I get 255
```

**Relevant Logs**

[//]: #  (The logs that where obtained by running the commands here. Please run the command with "-v" so that we can see the verbose logs.)

```
Start building sites … 
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=mage
ERROR 2022/04/26 16:48:50 [en] REF_NOT_FOUND: Ref "../Reference/agc_logs": "/home/anovak/workspace/amazon-genomics-cli/site/content/en/docs/Concepts/logs.md:43:79": page not found
ERROR 2022/04/26 16:48:50 [en] REF_NOT_FOUND: Ref "../Reference/agc_account": "/home/anovak/workspace/amazon-genomics-cli/site/content/en/docs/Concepts/accounts.md:40:53": page not found
ERROR 2022/04/26 16:48:50 [en] REF_NOT_FOUND: Ref "../Reference/agc_context": "/home/anovak/workspace/amazon-genomics-cli/site/content/en/docs/Concepts/contexts.md:128:49": page not found
ERROR 2022/04/26 16:48:50 [en] REF_NOT_FOUND: Ref "../Reference/agc_project": "/home/anovak/workspace/amazon-genomics-cli/site/content/en/docs/Concepts/projects.md:113:60": page not found
ERROR 2022/04/26 16:48:50 [en] REF_NOT_FOUND: Ref "../Reference/agc_workflow": "/home/anovak/workspace/amazon-genomics-cli/site/content/en/docs/Concepts/workflows.md:124:60": page not found
WARN 2022/04/26 16:48:51 .Path when the page is backed by a file is deprecated and will be removed in a future release. We plan to use Path for a canonical source path and you probably want to check the source is a file. To get the current behaviour, you can use a construct similar to the one below:

  {{ $path := "" }}
  {{ with .File }}
	{{ $path = .Path }}
  {{ else }}
	{{ $path = .Path }}
  {{ end }}


Re-run Hugo with the flag --panicOnWarning to get a better error message.
Error: Error building site: logged 5 error(s)
Total in 755 ms
```

**Expected Behavior**

[//]: #  (A clear and concise description of what you expected to happen.)

The documentation build should succeed.

**Actual Behavior**

[//]: #  (A clear and concise description of what actually happened.)

The documentation build fails (see above log).

**Screenshots**

[//]: #  (If applicable, add screenshots to help explain your problem.)

Ugly unstyled partially-generated documentation:
![image](https://user-images.githubusercontent.com/5062495/165390753-3bed7b71-ac9d-4a52-9103-eb3d8c24b3fe.png)

**Additional Context**

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System: Ubuntu 20.04
AGC Version: cc838eff100f1ef5b97439c298035542f2d6cc23
Was AGC setup with a custom bucket: N/A
Was AGC setup with a custom VPC: N/A

**Comment by adamnovak** [comment]
I've tried:

```
cd d /home/anovak/workspace/amazon-genomics-cli
(cd /home/anovak/workspace/amazon-genomics-cli/packages/cli && go mod vendor) && make build
packages/cli/bin/local/agc
cd site
../packages/cli/bin/local/agc
```

According to [this part of the docs README](https://github.com/aws/amazon-genomics-cli/blob/main/site/README.md#command-reference-generation) that's supposed to generate the missing files. But it doesn't:

```
ls content/en/docs/Reference/
_index.md
```

**Comment by adamnovak** [comment]
The answer is that the command to generate the reference docs should actually be something like:

```
packages/cli/bin/local/agc --docs site/content/en/docs/Reference
```

If you run `make docs` it knows how to do this for you, but I was running the pieces myself.

**Comment by markjschreiber** [comment]
I think we should change all the instructions to refer to the make commands as this is how we build the docs for production.
