### ISSUE TITLE
Demo CWL workflows should exercise S3 data import

### ISSUE THREAD

**Issue by adamnovak** [aws/amazon-genomics-cli#444]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  (A short description of the feature you are proposing.)

The CWL demo workflows included to demonstrate Toil don't import any pre-existing input data from S3. They ought to demonstrate importing both CWL `File`s and `Directory`s from S3.

**Use Case**

[//]: #  (Why do you need this feature?)
This would make sure that this functionality actually works.

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)
Some of the other demos already use data from https://registry.opendata.aws/ and declare data sources to access them: https://github.com/aws/amazon-genomics-cli/blob/main/examples/gatk-best-practices-project/agc-project.yaml#L50-L58

**Other information**

[//]: #  (detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc)

**Comment by markjschreiber** [comment]
Implemented
