### ISSUE TITLE
compute environment MaxvCPUs

### ISSUE THREAD

**Issue by genecentric** [aws/amazon-genomics-cli#46]
Question: 
When we run very large Nextflow workflows through Batch, we often need significantly more than 256 vCPUs within a Compute Environment to avoid extremely large run times and to maximize the benefit of using cloud resources.  The Compute Environments that started with my context were set at 256.  I know that this is one of the few settings that can actually be changed on the fly within the AWS console but could this be set as part of the context similar to the way that instance types can be selected?  Typically we have set ours at 5000.

**Comment by genecentric** [comment]
sorry just realized this is duplicate to issue#31
https://github.com/aws/amazon-genomics-cli/issues/31

**Comment by wleepang** [comment]
No worries. Will use #31 as the main issue and close this one.
