### ISSUE TITLE
Use public subnets for Cromwell

### ISSUE THREAD

**Issue by crabhi** [aws/amazon-genomics-cli#477]
[//]: #  (Before raising the feature request, please check to see if an existing feature request already exists.)

**Description**

[//]: #  (A short description of the feature you are proposing.)

The [AGC accounts docs](https://aws.github.io/amazon-genomics-cli/docs/concepts/accounts/) mention that `--usePublicSubnets` will fail with Cromwell because it's insecure. I'd like to figure out a way to use public subnets with Cromwell as well.

**Use Case**

[//]: #  (Why do you need this feature?)

Similarly to #269, my motivation is to reduce costs associated with NAT Gateways and PrivateLink that are used with private subnets. My concern is not only the hourly cost of these resources but also the increased data transfer costs (docker images download and S3 data transfer).

**Proposed Solution**

[//]: #  (Please include prototype/workaround/sketch/reference implementation.)

Comparing the architecture of [Cromwell](https://aws.github.io/amazon-genomics-cli/docs/workflow-engines/cromwell/) and [Nextflow](https://aws.github.io/amazon-genomics-cli/docs/workflow-engines/nextflow/) integration, I suppose the main difference is probably that Cromwell exposes a REST service.

If I understand it correctly, I see two possible options:

1. Rely on correct setting of Security Groups to prevent unauthorized Cromwell server access.
2. Or run Cromwell server (and probably the WES adapter as well?) in a private subnet, but execute the actual jobs in public subnets.

Is any of these options feasible? Would you accept a patch?

**Comment by markjschreiber** [comment]
A patch would be great!

The main issue is that Cromwell itself can be secured but it needs to be accessed by a lambda function via an elastic load balancer. The challenge is going to be securing the ELB so that only the associated lambda can call it. If the ELB remains unsecured then anyone can submit API calls (or DDOS) to Cromwell as soon as a port sniffer detects the IP of the ELB.

2 would definitely work but the goal of using only public subnets is to avoid the ongoing costs of NAT gateways. Any use of a private subnet would require the NAT gateway (or a VPC endpoint).

**Comment by crabhi** [comment]
Hello from Prague, Mark 👋 - we met briefly working for Merck.

Thanks for the clarification. That definitely helped. I'll investigate a bit more. Even the second option is an improvement because it avoids the data transfer costs for the tasks themselves.

Another option I'm considering is a bespoke setup with Cromwell listening on 127.0.0.1 on a server, integrated with AWS Batch, and users submitting jobs from a remote shell via Oliver. Obviously, the AGC approach is much more versatile.

**Comment by markjschreiber** [comment]
I thought I recognized the name.

If you don't want to use AGC then an alternative would be to run Cromwell with it's REST server and use AWS Cognito and API Gateway to produce a public yet secured REST or Web front end.

**Comment by crabhi** [comment]
I'm no longer working on this. My client preferred a simpler Cromwell-only setup, so I didn't get to tweak the AGC tool.

We settled on a configuration based on the [Genomic Workflows on AWS tutorial](https://docs.opendata.aws/genomics-workflows/quick-start.html) but using public subnets and a customized EC2 instance running the Cromwell server.

It surprised me that Cromwell didn't work with just any AWS Batch cluster. It turns out the magic is in the EC2 launch template configured for the Batch environment. Its user script downloads extra scripts from S3 bucket provisioned by the GWF Core template. Cromwell's AWS Batch backend relies on these additions.

Thanks again for your comments!
