### ISSUE TITLE
Log groups for miniwdl head jobs are not /aws/batch/job

### ISSUE THREAD

**Issue by nh13** [aws/amazon-genomics-cli#483]
Looking at the [`Batch.Client.describe_jobs`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/batch.html#Batch.Client.describe_jobs) method, I see it returns the _log stream name_, but not the _log group name_.  The log group is said to always be `/aws/batch/job`.  

When I look at the cloudwatch log for the miniwdl head job, it starts with `Agc-Context-...` instead, so I can't use the boto3 API.  Any chance this could be configured to be the standard `/aws/batch/job` log group?

**Comment by wleepang** [comment]
Engines like MiniWDL use a custom LogGroup for the head job. This is to support the `agc logs engine` command. In these cases if you know the head job id, you can get the corresponding LogGroup via:

```bash
aws batch describe-jobs \
  --jobs <job-id> \
  --query 'jobs[0].container.logConfiguration.options."awslogs-group"' \
  --output text
```

**Comment by wleepang** [comment]
LogGroup names are generated based on user-id, project name, context name, and engine. They can't be set to a custom value that is outside of these dimensions (which are mostly defined in the `agc-project.yaml` file). That said, resources that `agc` creates are tagged by these dimensions as well, so if you know, for example, the value of `agc-context` (or other combination of AGC specific tags), you can do something like following to get its corresponding LogGroup name:

```bash
aws resource-groups search-resources \
  --resource-query '{"Type": "TAG_FILTERS_1_0", "Query": "{\"ResourceTypeFilters\": [\"AWS::Logs::LogGroup\"], \"TagFilters\": [{\"Key\": \"agc-context\", \"Values\": [\"<context-name>\"]}]}"}'
```
