### ISSUE TITLE
Allow environments without external DNS to deploy engines using EFS

### ISSUE THREAD

**Issue by crabba** [aws/amazon-genomics-cli#493]
**Description**

Currently, CDK deployment of Fargate instances mounting EFS volumes requires that the environment have access to AWS DNS. Environments with custom DNS are therefore unable to deploy engines such as Snakemake, which use EFS.

**Use Case**

Wish to run Snakemake in AGC, and have a requirement to use custom DNS.

**Proposed Solution**

Mounting an EFS volume onto a Fargate instance by using IP addresses rather than DNS, would allow this use case.

**Comment by markjschreiber** [comment]
Hi -

I have researched this and unfortunately it is not possible to implement at this time. aWhen including EFS in the container definition of a Batch task you may only enter the Fargate filesystem ID and Access point ID. There is no mechanism to insert either a IP or DNS name. Presumably Batch instances do this lookup behind the scenes. It seems that a change would need to be made to the Batch service (and maybe ECS) to allow this.
