### ISSUE TITLE
overriding upper limits on memory and cpus

### ISSUE THREAD

**Issue by jhgraber** [aws/amazon-genomics-cli#495]
I am trying to use AGC in conjunction with the nf-core/rnaseq workflow, specifically in the challenging case of the axolotl (Ambystoma mexicanum) genome, which is roughly ten times larger than human.  I have not been able to override the memory limits for either the star or salmon steps of the process.  

All salmon quant and star alignment steps are failing with an exit code of 137, which indicates inadequate memory

Among the steps I have tried to fix this issue are: 

prebuilding the salmon index and the star index (built independently on an r5.12xlarge instance

changing the max-cpus and max-memory options handed directly to the workflow call (using inputs.json), and also providing a custom nextflow.config file that included either this:

process {
    withName: 'NFCORE_RNASEQ:RNASEQ:ALIGN_STAR:STAR_ALIGN' {
        memory = 360.GB
    }
    withName: 'NFCORE_RNASEQ:RNASEQ:QUANTIFY_SALMON:SALMON_QUANT' {
        memory = 220.GB
    }
}

and also 
    withLabel:process_high {
        cpus   = { check_max( 24    * task.attempt, 'cpus'    ) }
        memory = { check_max( 320.GB * task.attempt, 'memory'  ) }
        time   = { check_max( 16.h  * task.attempt, 'time'    )
    }

With some feedback after the last failures, I was directed to the AWS Batch console, and found that in all cases, the requested memory was the standard 72GB (for the star)

I have tested an exact case of this with the same r5.12xlarge machine and found that with 40 CPU threads, the alignment took about 47 minutes and consumed a peak of about 305GB of RAM.

I really just need to know how to override the memory request for both the star alignment, and also the salmon quantification steps.

The logs have already been shared with some of the agc team.
**Expected Behavior**

A
[//]: #  (A clear and concise description of what you expected to happen.)

**Actual Behavior**

[//]: #  (A clear and concise description of what actually happened.)

**Screenshots**

[//]: #  (If applicable, add screenshots to help explain your problem.)

**Additional Context**

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System:
AGC Version:
Was AGC setup with a custom bucket:
Was AGC setup with a custom VPC:

**Comment by markjschreiber** [comment]
The list of EC2 types deployed to the default compute environments may not be sufficiently sized to fulfill your requested CPU/ memory. You can specify instance types used for a context as [described here](https://aws.github.io/amazon-genomics-cli/docs/concepts/contexts/#instance-types)

If this doesn't resolve the issue please feel free to re-open this issue.
