### ISSUE TITLE
agc account deactivate fails silently

### ISSUE THREAD

**Issue by coverbeck** [aws/amazon-genomics-cli#502]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

An `agc account deactivate` did not deactivate the account, but gave no feedback saying it had failed.

**Steps to Reproduce**

1. A user, Joe, sets up AGC then leaves the organization
2. Another user, Jane, wants to clean up, does not have access to Joe's project nor context files, and Joe has left, so Jane tries to deactivate the account with `agc account deactivate`.
3. The command immediately returned with the message "Deactivating AGC. Deactivation may take up to 5 minutes to complete and return".
4. We looked at CloudFormation in the AWS Console UI, and nothing happened. 
5. No resources were deleted, no error message was displayed.

**Relevant Logs**

I did not capture any logs

**Expected Behavior**

I would expect the command to work, or failing that, an error message saying why it didn't work.

**Actual Behavior**

Step 3 in steps to reproduce -- a message implying it would work, but nothing was deactivated, and no error message was displayed.

**Screenshots**

None captured

**Additional Context**

We ended up deleting the stacks via the CloudFormation UI. Then we found out that we should have used the `--force` switch. But we'd already deleted the stacks manually.

Operating System:
AGC Version: 1.2.0 (yes, it's old)
Was AGC setup with a custom bucket: I don't recall
Was AGC setup with a custom VPC: I don't recall

**Comment by markjschreiber** [comment]
I believe this has been fixed in newer versions. The user should now be told that contexts are deployed and must be deleted or force deleted. At this point we are not making fixes to old versions of AGC. Is upgrading an option for you?

**Comment by coverbeck** [comment]
> I believe this has been fixed in newer versions. The user should now be told that contexts are deployed and must be deleted or force deleted. At this point we are not making fixes to old versions of AGC. Is upgrading an option for you?

Yes upgrading is an option; if this comes up again, I'll upgrade first.
