### ISSUE TITLE
Nextflow version

### ISSUE THREAD

**Issue by jmbaek** [aws/amazon-genomics-cli#510]
[//]: #  (Please do not include your AWS account or credentials as part of the bug request.)

**Describe the Bug**

[//]: #  (Please describe the behavior that you are seeing with as many details as possible including logs from AGC, CloudWatch snippets and CloudFormation errors if relevant.)

**Steps to Reproduce**

[//]: #  (Include a list of steps that can be used to reproduce the bug.)

**Relevant Logs**

[//]: #  (The logs that where obtained by running the commands here. Please run the command with "-v" so that we can see the verbose logs.)

**Expected Behavior**

[//]: #  (A clear and concise description of what you expected to happen.)

**Actual Behavior**

[//]: #  (A clear and concise description of what actually happened.)

**Screenshots**

[//]: #  (If applicable, add screenshots to help explain your problem.)

**Additional Context**

[//]: #  (Add any other context about the problem here. The minimum required information is below)

Operating System:
AGC Version:
Was AGC setup with a custom bucket:
Was AGC setup with a custom VPC:

**Comment by jmbaek** [comment]
I'm running the most recent version of AGC v1.5.0.
When I tried to run the sarek example, this error popped up;
nextflow.exception.AbortOperationException: Nextflow version 21.04.3 does not match workflow required version: >=21.10.3

Check the nf-core page and newer sarek requires nextflow >=21.10.
How can I update the nextflow version in AGC?

**Comment by wleepang** [comment]
We'll be addressing this in a future release. Code to update the version of Nextflow used is here: #450 

For the time being you will need to use a version of the Sarek workflow that accepts Nextflow 21.04.3 using the `-r` flag in `engineOptions`.

**Comment by wleepang** [comment]
Resolved in #450 and release 1.5.1
