### ISSUE TITLE
Upgrade fails from 1.5.0 to 1.5.2

### ISSUE THREAD

**Issue by bounlu** [aws/amazon-genomics-cli#554]
I get this notification:
`2022-11-01T22:35:01+08:00 𝒊  New version of agc available. Current version is '1.5.0'. The latest version is '1.5.2'. Please consider upgrading to the latest version by following https://aws.github.io/amazon-genomics-cli/docs/getting-started/installation/ `

I install the new version by following:
https://aws.github.io/amazon-genomics-cli/docs/getting-started/installation/

I check the version:
```
$ agc --version
agc version: 1.5.0
```

It's still the old version and I keep receiving the notification in new terminal windows.

**Comment by vvalleru** [comment]
Hello Omar, 

Thanks for reaching out! I was able to download the [amazon-genomics-cli-1.5.2.zip](https://github.com/aws/amazon-genomics-cli/releases/download/v1.5.2/amazon-genomics-cli-1.5.2.zip) and successfully install the 1.5.2 release on my Mac. 

Can you elaborate more on which binary you downloaded and the operating system you used? 

Thank you.

**Comment by bounlu** [comment]
Ohh got it now, I had just copy pasted the command on the page:
`aws s3api get-object --bucket healthai-public-assets-us-east-1 --key amazon-genomics-cli/nightly-build/amazon-genomics-cli.zip amazon-genomics-cli.zip`

which gave me the nightly build.

Once I specified the version, as below it worked fine.
`wget https://github.com/aws/amazon-genomics-cli/releases/download/v1.5.2/amazon-genomics-cli-1.5.2.zip`
